#!/usr/bin/env python3
"""
WordPress記事にカテゴリ別アイキャッチ画像を一括設定するスクリプト

Usage:
    python3 set_featured_images.py              # 実行
    python3 set_featured_images.py --dry-run    # ドライラン（変更なし）

処理フロー:
  1. NAS上の写真を1200x630にリサイズ（JPEG品質85%）
  2. 赤外線カテゴリ用OGP画像をPillowで自動生成
  3. WordPress Media Libraryにアップロード
  4. 記事タイトル・スラッグからカテゴリ判定
  5. featured_mediaを設定（既存設定済みはスキップ）
"""

import argparse
import base64
import glob
import json
import logging
import os
import re
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    print("ERROR: Pillow が必要です。 pip install Pillow")
    sys.exit(1)

# ── Paths ──
SCRIPT_DIR = Path(__file__).parent
TMP_DIR = Path("/tmp/featured_images")
OGP_WIDTH = 1200
OGP_HEIGHT = 630
JPEG_QUALITY = 85
API_SLEEP = 0.5

# ── Logging ──
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)

# ── NAS Photo Sources ──
PHOTO_SOURCES = {
    "drone_survey": "/mnt/nas3/meetsmore_photos/DJI_0662.JPG",
    "earthwork": None,  # Will be resolved from ららぽーと安城 folder
    "factory": "/mnt/nas4/1_Projects/UAV_survey_data/2021-09-15武豊火力発電所/DJI_0596.JPG",
    "inventory": "/mnt/nas4/1_Projects/UAV_survey_data/2023-11-07名古屋埠頭/DJI_0074.JPG",
    "iconstruction": "/mnt/nas3/meetsmore_photos/DJI_0663.JPG",
    "infrared": None,  # Generated by Pillow
}

LALAPOR_DIR = "/mnt/nas4/1_Projects/UAV_survey_data/2023-06-27_ららぽーと安城_平均地盤測量"

# ── Category Keyword Rules ──
CATEGORY_RULES = [
    (
        "inventory",
        "在庫計測",
        ["在庫", "棚卸", "パイル", "石炭", "PKS", "木質チップ", "砂利", "砕石", "鉱石", "サイロ", "穀物", "燃料"],
    ),
    (
        "factory",
        "工場・プラント",
        ["工場", "プラント", "BCP", "設備", "スキャン", "配管", "不陸", "スラブ"],
    ),
    (
        "infrared",
        "赤外線調査",
        ["赤外線", "外壁", "点検", "太陽光パネル"],
    ),
    (
        "earthwork",
        "土量計算・造成",
        ["土量", "残土", "ダンプ", "造成", "切土", "盛土", "搬出", "処分", "積算"],
    ),
    (
        "iconstruction",
        "i-Construction・BIM",
        ["i-Construction", "BIM", "CIM", "出来形", "IFC", "LandXML"],
    ),
]

DEFAULT_CATEGORY = ("drone_survey", "ドローン測量")


# ── Config ──
def load_config():
    """automation_config.jsonから認証情報を読み込み"""
    candidates = [
        Path("/mnt/c/Users/USER/Documents/_data/automation_config.json"),
        SCRIPT_DIR / "automation_config.json",
    ]
    for p in candidates:
        if p.exists():
            with open(p) as f:
                cfg = json.load(f)
            # Resolve ${ENV_VAR} placeholders
            return _resolve_env_vars(cfg)
    raise FileNotFoundError(
        "automation_config.json not found. Searched: " + ", ".join(str(p) for p in candidates)
    )


def _resolve_env_vars(obj):
    """Recursively resolve ${ENV_VAR} placeholders in config values."""
    if isinstance(obj, dict):
        return {k: _resolve_env_vars(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_resolve_env_vars(v) for v in obj]
    if isinstance(obj, str):
        pattern = re.compile(r"\$\{(\w+)\}")
        match = pattern.fullmatch(obj.strip())
        if match:
            env_val = os.environ.get(match.group(1), obj)
            return env_val
        # Partial replacement
        def replacer(m):
            return os.environ.get(m.group(1), m.group(0))
        return pattern.sub(replacer, obj)
    return obj


def get_wp_auth(cfg):
    user = cfg["wordpress"]["user"]
    pwd = cfg["wordpress"]["app_password"]
    return base64.b64encode(f"{user}:{pwd}".encode()).decode()


# ── Image Processing ──
def resize_image(src_path: str, dst_path: str):
    """画像を1200x630にリサイズしてJPEG保存（中央クロップ）"""
    with Image.open(src_path) as img:
        img = img.convert("RGB")
        # Center crop to OGP aspect ratio
        src_w, src_h = img.size
        target_ratio = OGP_WIDTH / OGP_HEIGHT
        src_ratio = src_w / src_h

        if src_ratio > target_ratio:
            # Source is wider: crop width
            new_w = int(src_h * target_ratio)
            offset = (src_w - new_w) // 2
            img = img.crop((offset, 0, offset + new_w, src_h))
        else:
            # Source is taller: crop height
            new_h = int(src_w / target_ratio)
            offset = (src_h - new_h) // 2
            img = img.crop((0, offset, src_w, offset + new_h))

        img = img.resize((OGP_WIDTH, OGP_HEIGHT), Image.LANCZOS)
        img.save(dst_path, "JPEG", quality=JPEG_QUALITY, optimize=True)
        log.info(f"  Resized: {Path(src_path).name} -> {dst_path} ({os.path.getsize(dst_path) // 1024}KB)")


def generate_infrared_image(dst_path: str):
    """赤外線カテゴリ用OGP画像を自動生成（#1647FB背景 + 白テキスト）"""
    img = Image.new("RGB", (OGP_WIDTH, OGP_HEIGHT), color=(22, 71, 251))
    draw = ImageDraw.Draw(img)

    # Try Noto Sans JP, fall back to default
    font = None
    font_paths = [
        "/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc",
        "/usr/share/fonts/noto-cjk/NotoSansCJK-Bold.ttc",
        "/usr/share/fonts/truetype/noto/NotoSansJP-Bold.ttf",
        "/usr/share/fonts/google-noto-cjk/NotoSansCJK-Bold.ttc",
        "/usr/share/fonts/OTF/NotoSansCJK-Bold.ttc",
    ]
    for fp in font_paths:
        if os.path.exists(fp):
            try:
                font = ImageFont.truetype(fp, 80)
                log.info(f"  Font loaded: {fp}")
                break
            except Exception:
                continue

    if font is None:
        try:
            font = ImageFont.truetype("DejaVuSans-Bold.ttf", 60)
        except Exception:
            font = ImageFont.load_default()
        log.warning("  Noto Sans JP not found, using default font")

    text = "赤外線調査"
    bbox = draw.textbbox((0, 0), text, font=font)
    tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
    x = (OGP_WIDTH - tw) // 2
    y = (OGP_HEIGHT - th) // 2

    # Subtle shadow for depth
    draw.text((x + 3, y + 3), text, fill=(10, 40, 180), font=font)
    draw.text((x, y), text, fill="white", font=font)

    # Add subtle line decoration
    line_y = y + th + 40
    line_w = 200
    draw.line(
        [(OGP_WIDTH // 2 - line_w, line_y), (OGP_WIDTH // 2 + line_w, line_y)],
        fill=(255, 255, 255, 180),
        width=3,
    )

    img.save(dst_path, "JPEG", quality=JPEG_QUALITY)
    log.info(f"  Generated infrared OGP: {dst_path} ({os.path.getsize(dst_path) // 1024}KB)")


def resolve_earthwork_photo():
    """ららぽーと安城フォルダからDJI写真を1枚選定"""
    if not os.path.isdir(LALAPOR_DIR):
        log.error(f"Earthwork photo dir not found: {LALAPOR_DIR}")
        return None

    photos = sorted(glob.glob(os.path.join(LALAPOR_DIR, "*.JPG")))
    photos += sorted(glob.glob(os.path.join(LALAPOR_DIR, "*.jpg")))
    if not photos:
        # Try subdirectories
        photos = sorted(glob.glob(os.path.join(LALAPOR_DIR, "**", "*.JPG"), recursive=True))
        photos += sorted(glob.glob(os.path.join(LALAPOR_DIR, "**", "*.jpg"), recursive=True))

    if photos:
        # Pick a photo from around the middle (likely better composition)
        selected = photos[len(photos) // 2]
        log.info(f"  Selected earthwork photo: {selected}")
        return selected

    log.error("No JPG files found in earthwork directory")
    return None


def prepare_images():
    """全カテゴリのリサイズ済み画像を準備"""
    TMP_DIR.mkdir(parents=True, exist_ok=True)

    # Resolve earthwork photo
    earthwork_photo = resolve_earthwork_photo()
    if earthwork_photo:
        PHOTO_SOURCES["earthwork"] = earthwork_photo

    prepared = {}

    for cat_key, src_path in PHOTO_SOURCES.items():
        dst_path = str(TMP_DIR / f"featured_{cat_key}.jpg")

        if cat_key == "infrared":
            generate_infrared_image(dst_path)
            prepared[cat_key] = dst_path
            continue

        if src_path is None:
            log.warning(f"  No source photo for category: {cat_key}")
            continue

        if not os.path.exists(src_path):
            log.error(f"  Source not found: {src_path}")
            continue

        resize_image(src_path, dst_path)
        prepared[cat_key] = dst_path

    return prepared


# ── WordPress API ──
def wp_request(url, cfg, method="GET", data=None, files=None):
    """WordPress REST API request with error handling"""
    auth = get_wp_auth(cfg)
    headers = {"Authorization": f"Basic {auth}"}

    if files:
        # Multipart file upload
        boundary = "----PythonBoundary" + str(int(time.time()))
        headers["Content-Type"] = f"multipart/form-data; boundary={boundary}"

        body_parts = []
        for field_name, (filename, filedata, content_type) in files.items():
            body_parts.append(f"--{boundary}".encode())
            body_parts.append(
                f'Content-Disposition: form-data; name="{field_name}"; filename="{filename}"'.encode()
            )
            body_parts.append(f"Content-Type: {content_type}".encode())
            body_parts.append(b"")
            body_parts.append(filedata)

        if data:
            for key, val in data.items():
                body_parts.append(f"--{boundary}".encode())
                body_parts.append(f'Content-Disposition: form-data; name="{key}"'.encode())
                body_parts.append(b"")
                body_parts.append(str(val).encode())

        body_parts.append(f"--{boundary}--".encode())
        body = b"\r\n".join(body_parts)
    elif data:
        headers["Content-Type"] = "application/json"
        body = json.dumps(data).encode()
    else:
        body = None

    req = urllib.request.Request(url, data=body, headers=headers, method=method)

    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            return json.loads(resp.read().decode())
    except urllib.error.HTTPError as e:
        error_body = e.read().decode() if e.fp else ""
        log.error(f"  HTTP {e.code}: {url}")
        log.error(f"  Response: {error_body[:500]}")
        raise
    except urllib.error.URLError as e:
        log.error(f"  URL Error: {e.reason} - {url}")
        raise


def upload_media(image_path: str, alt_text: str, cfg, dry_run=False):
    """画像をWordPress Media Libraryにアップロード"""
    filename = os.path.basename(image_path)
    base_url = cfg["wordpress"]["base_url"]
    url = f"{base_url}/media"

    if dry_run:
        log.info(f"  [DRY-RUN] Would upload: {filename} (alt: {alt_text})")
        return {"id": -1}

    with open(image_path, "rb") as f:
        filedata = f.read()

    files = {
        "file": (filename, filedata, "image/jpeg"),
    }
    data = {
        "alt_text": alt_text,
        "title": alt_text,
    }

    result = wp_request(url, cfg, method="POST", files=files, data=data)
    media_id = result.get("id")
    log.info(f"  Uploaded: {filename} -> Media ID: {media_id}")
    time.sleep(API_SLEEP)
    return result


def get_all_posts(cfg):
    """全記事を取得（ページネーション対応）"""
    base_url = cfg["wordpress"]["base_url"]
    all_posts = []
    page = 1
    per_page = 100

    while True:
        url = f"{base_url}/posts?per_page={per_page}&page={page}&_fields=id,title,slug,featured_media,categories,status"
        try:
            posts = wp_request(url, cfg)
        except urllib.error.HTTPError as e:
            if e.code == 400:
                # No more pages
                break
            raise

        if not posts:
            break

        all_posts.extend(posts)
        log.info(f"  Fetched page {page}: {len(posts)} posts")

        if len(posts) < per_page:
            break
        page += 1
        time.sleep(API_SLEEP)

    return all_posts


def classify_post(post):
    """記事タイトル・スラッグからカテゴリを判定"""
    title = post.get("title", {}).get("rendered", "")
    slug = post.get("slug", "")
    text = f"{title} {slug}".lower()

    for cat_key, cat_label, keywords in CATEGORY_RULES:
        for kw in keywords:
            if kw.lower() in text:
                return cat_key, cat_label
    return DEFAULT_CATEGORY


def set_featured_image(post_id, media_id, cfg, dry_run=False):
    """記事にアイキャッチ画像を設定"""
    base_url = cfg["wordpress"]["base_url"]
    url = f"{base_url}/posts/{post_id}"

    if dry_run:
        log.info(f"  [DRY-RUN] Would set post {post_id} featured_media = {media_id}")
        return

    result = wp_request(url, cfg, method="POST", data={"featured_media": media_id})
    time.sleep(API_SLEEP)
    return result


# ── Main ──
def main():
    parser = argparse.ArgumentParser(description="WordPress記事にカテゴリ別アイキャッチ画像を一括設定")
    parser.add_argument("--dry-run", action="store_true", help="変更を実行せず、処理内容のみ表示")
    args = parser.parse_args()

    if args.dry_run:
        log.info("=== DRY-RUN MODE ===")

    # Load config
    log.info("Loading config...")
    cfg = load_config()
    wp_cfg = cfg.get("wordpress", {})
    if not wp_cfg.get("base_url") or not wp_cfg.get("app_password"):
        log.error("WordPress config incomplete. Check automation_config.json")
        sys.exit(1)

    # Step 1: Prepare images
    log.info("=" * 60)
    log.info("Step 1: Preparing category images...")
    log.info("=" * 60)
    prepared = prepare_images()
    log.info(f"Prepared {len(prepared)} category images: {list(prepared.keys())}")

    if not prepared:
        log.error("No images prepared. Aborting.")
        sys.exit(1)

    # Step 2: Upload images to WP Media Library
    log.info("=" * 60)
    log.info("Step 2: Uploading images to WordPress...")
    log.info("=" * 60)
    media_ids = {}
    cat_labels = {key: label for key, label, _ in CATEGORY_RULES}
    cat_labels["drone_survey"] = "ドローン測量"

    for cat_key, img_path in prepared.items():
        alt_text = cat_labels.get(cat_key, "ドローン測量")
        try:
            result = upload_media(img_path, alt_text, cfg, dry_run=args.dry_run)
            media_ids[cat_key] = result.get("id", -1)
        except Exception as e:
            log.error(f"  Failed to upload {cat_key}: {e}")
            continue

    log.info(f"Uploaded {len(media_ids)} images: {media_ids}")

    # Step 3: Fetch all posts
    log.info("=" * 60)
    log.info("Step 3: Fetching all posts...")
    log.info("=" * 60)
    posts = get_all_posts(cfg)
    log.info(f"Total posts: {len(posts)}")

    # Step 4: Classify and set featured images
    log.info("=" * 60)
    log.info("Step 4: Setting featured images...")
    log.info("=" * 60)

    stats = {
        "skipped_already_set": 0,
        "skipped_no_media": 0,
        "updated": 0,
        "failed": 0,
    }
    category_counts = {}

    for post in posts:
        post_id = post["id"]
        title = post.get("title", {}).get("rendered", "(no title)")
        current_featured = post.get("featured_media", 0)

        # Skip if already has featured image
        if current_featured and current_featured > 0:
            log.info(f"  SKIP (already set): [{post_id}] {title[:50]}")
            stats["skipped_already_set"] += 1
            continue

        # Classify
        cat_key, cat_label = classify_post(post)
        category_counts[cat_label] = category_counts.get(cat_label, 0) + 1

        # Check if we have a media ID for this category
        if cat_key not in media_ids:
            log.warning(f"  SKIP (no media): [{post_id}] {title[:50]} -> {cat_label}")
            stats["skipped_no_media"] += 1
            continue

        media_id = media_ids[cat_key]
        log.info(f"  SET: [{post_id}] {title[:50]} -> {cat_label} (media_id={media_id})")

        try:
            set_featured_image(post_id, media_id, cfg, dry_run=args.dry_run)
            stats["updated"] += 1
        except Exception as e:
            log.error(f"  FAILED: [{post_id}] {title[:50]} - {e}")
            stats["failed"] += 1

    # Summary
    log.info("=" * 60)
    log.info("SUMMARY")
    log.info("=" * 60)
    log.info(f"  Total posts:          {len(posts)}")
    log.info(f"  Already had image:    {stats['skipped_already_set']}")
    log.info(f"  No media available:   {stats['skipped_no_media']}")
    log.info(f"  Updated:              {stats['updated']}")
    log.info(f"  Failed:               {stats['failed']}")
    log.info("")
    log.info("Category distribution (posts without featured image):")
    for cat, count in sorted(category_counts.items(), key=lambda x: -x[1]):
        log.info(f"  {cat}: {count}")


if __name__ == "__main__":
    main()
